apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: nats
  labels:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
  ports:
    - name: client
      appProtocol: tcp
      protocol: TCP
      port: 4222
      targetPort: 4222
