cluster:
  enabled: true

  # Quorum-based RAFT consensus
  replicas: 3

  # Disable advertising to enable
  # external access to the cluster.
  noAdvertise: true

nats:
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: 1Gi

    fileStorage:
      enabled: true
      size: 10Gi
