resources:
  - ../../../../charts/argocd/base

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: platform
    patch: |-
      - op: replace
        path: /spec/sources/0/path
        value: 'overlays/home/lab'

  - target:
      group: argoproj.io
      kind: ApplicationSet
      name: helm-components
    patch: |-
      - op: replace
        path: /spec/template/spec/sources/0/helm/valueFiles/1
        value: '$values/envs/home/lab/{{.path.basename}}/values.yaml'
      - op: replace
        path: /spec/template/spec/sources/2/path
        value: 'envs/home/lab/{{.path.basename}}'
