apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: east-west-ingress
  namespace: istio-ingress
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: east-west-ingress
      istio: east-west-ingress
