service:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: 4222

autoscaling:
  minReplicas: 2

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
